import { MealPlanConfig, MenuCategory, TargetType } from './types';
import { REAL_MENU_DB } from './data/realMenuDB';

// 실제 반찬 시트 데이터 기반 메뉴 DB (215개 아이템)
export const MOCK_MENU_DB = REAL_MENU_DB;

export const MAJOR_INGREDIENTS = [
  { key: 'beef', label: '소고기' },
  { key: 'pork', label: '한돈' },
  { key: 'chicken', label: '닭' },
  { key: 'fish', label: '생선' },
  { key: 'tofu', label: '두부' },
  { key: 'egg', label: '달걀' },
  { key: 'potato', label: '감자' },
  { key: 'seaweed', label: '해조류' },
  { key: 'mushroom', label: '버섯' },
  { key: 'vegetable', label: '채소' },
];

export const TARGET_CONFIGS: Record<TargetType, MealPlanConfig> = {
  [TargetType.KIDS]: {
    target: TargetType.KIDS,
    budgetCap: 11040, // 30% of 36800
    targetPrice: 36800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 3 },
    bannedTags: ['매운맛', '얼큰함'],
    requiredTags: ['아이선호'],
  },
  [TargetType.KIDS_PLUS]: {
    target: TargetType.KIDS_PLUS,
    budgetCap: 14640, // 30% of 48800
    targetPrice: 48800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 6 },
    bannedTags: ['매운맛'],
    requiredTags: ['아이선호'],
    parentTarget: TargetType.KIDS, // Explicit inheritance
  },
  [TargetType.SIDE_ONLY]: {
    target: TargetType.SIDE_ONLY,
    budgetCap: 10440,
    targetPrice: 34800,
    targetCostRatio: 30,
    composition: { [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 5 }, // 국 없음
    bannedTags: [],
    requiredTags: [],
  },
  [TargetType.SENIOR]: {
    target: TargetType.SENIOR,
    budgetCap: 11940,
    targetPrice: 39800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 4 },
    bannedTags: ['질김'],
    requiredTags: ['시니어'],
  },
  [TargetType.SENIOR_HEALTH]: {
    target: TargetType.SENIOR_HEALTH,
    budgetCap: 13980,
    targetPrice: 46600,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 4 },
    bannedTags: ['질김', '딱딱함'],
    requiredTags: ['시니어', '부드러움'],
    parentTarget: TargetType.SENIOR,
  },
  [TargetType.YOUTH]: {
    target: TargetType.YOUTH,
    budgetCap: 13440,
    targetPrice: 44800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 2, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 3 },
    bannedTags: [],
    requiredTags: [],
  },
  [TargetType.YOUTH_MAIN]: {
    target: TargetType.YOUTH_MAIN,
    budgetCap: 10440,
    targetPrice: 34800,
    targetCostRatio: 30,
    composition: { [MenuCategory.MAIN]: 2, [MenuCategory.SIDE]: 3 }, // 국 없음, 메인 2개
    bannedTags: [],
    requiredTags: [],
    parentTarget: TargetType.YOUTH,
  },
  [TargetType.VALUE]: {
    target: TargetType.VALUE,
    budgetCap: 11040,
    targetPrice: 36800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 4 },
    bannedTags: [],
    requiredTags: [],
  },
  [TargetType.FAMILY]: {
    target: TargetType.FAMILY,
    budgetCap: 14940,
    targetPrice: 49800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 2, [MenuCategory.MAIN]: 2, [MenuCategory.SIDE]: 2 },
    bannedTags: [],
    requiredTags: [],
  },
  [TargetType.FAMILY_PLUS]: {
    target: TargetType.FAMILY_PLUS,
    budgetCap: 17640,
    targetPrice: 58800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 2, [MenuCategory.MAIN]: 2, [MenuCategory.SIDE]: 4 },
    bannedTags: [],
    requiredTags: [],
    parentTarget: TargetType.FAMILY,
  },
  [TargetType.FIRST_MEET]: {
    target: TargetType.FIRST_MEET,
    budgetCap: 8940,
    targetPrice: 29800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 3 },
    bannedTags: ['매운맛'],
    requiredTags: [],
  },
  [TargetType.TODDLER_PLUS]: {
    target: TargetType.TODDLER_PLUS,
    budgetCap: 13440,
    targetPrice: 44800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 5 },
    bannedTags: ['매운맛', '질김'],
    requiredTags: [],
    parentTarget: TargetType.TODDLER,
  },
  [TargetType.TODDLER]: {
    target: TargetType.TODDLER,
    budgetCap: 10440,
    targetPrice: 34800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 3 },
    bannedTags: ['매운맛', '질김'],
    requiredTags: [],
  },
  [TargetType.CHILD_PLUS]: {
    target: TargetType.CHILD_PLUS,
    budgetCap: 14640,
    targetPrice: 48800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 6 },
    bannedTags: ['매운맛'],
    requiredTags: [],
    parentTarget: TargetType.CHILD,
  },
  [TargetType.CHILD]: {
    target: TargetType.CHILD,
    budgetCap: 11040,
    targetPrice: 36800,
    targetCostRatio: 30,
    composition: { [MenuCategory.SOUP]: 1, [MenuCategory.MAIN]: 1, [MenuCategory.SIDE]: 3 },
    bannedTags: ['매운맛'],
    requiredTags: [],
  },
};
